version: '3'

services:
  web:
    build:
      context: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '5000:5000'
    environment:
      DEBUG: 'socket.io:*'
    command: ['yarn', 'start']
